bash script gets environments from gh api

diff --git a/.github/workflows/loopclients.yml b/.github/workflows/loopclients.yml
--- a/.github/workflows/loopclients.yml
+++ b/.github/workflows/loopclients.yml
@@ -12,14 +12,32 @@ jobs:
             enviros: ${{ steps.getenvs.outputs.envs }}
         steps:
             - id: getenvs
-              run: |
-                res=$(curl -L \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${{github.token}}" \
-                -H "X-GitHub-Api-Version: 2022-11-28" \
-                https://api.github.com/repos/${{github.repository}}/environments)
-                echo "$res"
-                echo 'envs=["Enviro1", "Customer"]' >> "$GITHUB_OUTPUT"
+              run: |            
+                environments=()
+                pageNum=1
+                total=1
+                
+                # Fetching environments
+                while [ ${#environments[@]} -lt $total ]; do
+                    res=$(curl -s -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{github.token}}" "https://api.github.com/repos/${{github.repository}}/environments?per_page=100&page=$pageNum")
+                    
+                    # Extracting data
+                    envs=($(echo "$res" | jq -r '.environments[].name'))
+                    total=$(echo "$res" | jq -r '.total_count')
+                    
+                    # Error handling
+                    if [ ${#envs[@]} -eq 0 ]; then
+                        echo "An error has occurred while attempting to fetch the environments"
+                        exit 1
+                    fi
+                    
+                    # Appending environments
+                    environments+=("${envs[@]}")
+                    ((pageNum++))
+                done
+                
+                printf '%s\n' "${environments[@]}" | jq -R . | jq -sc . >> "$GITHUB_OUTPUT"
+                
     matrixenvironments:
         needs: getenvironments
         # this method is able to repeat the job for every environment
